name: Setup Bun
on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
      - development
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - main
      - development
  workflow_dispatch:
jobs:
  setup-bun:
    runs-on: ubuntu-latest
    steps:
      - run: cd backend
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun run test:coverage
