name: Setup Bun
on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
      - development
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - main
      - development
  workflow_dispatch:
jobs:
  setup-bun:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
        bun-version:
          - latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-bun
        name: Setup Bun
        uses: ./backend
        with:
          bun-version: ${{ matrix.bun-version }}
      - id: verify-bun
        name: Verify Bun
        run: |
          bun --version
      - id: install-packages
        name: Install packages
        run: |
          bun install
      - id: run-tests
        name: Run Tests
        run: |
          bun run test:coverage
